import './styles.css';
const K='berged-v01';
const s=JSON.parse(localStorage.getItem(K)||'null')||{page:'home',posts:[['Mira','@mira','Bugün Berged’de ilk paylaşımımı yaptım. ✦',24],['Arda','@arda','Akşam için plan hazır. Kimler geliyor?',41]],messages:[['Mira','Az önce gönderdiğin videoyu gördüm 👀'],['Arda','Tamamdır, 20:30?'],['Lina','🔥 serimiz devam ediyor']],expenses:[],streaks:[['Lina',18],['Arda',7]]};
const A=document.querySelector('#app');const esc=x=>String(x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function save(){localStorage.setItem(K,JSON.stringify(s))}
function layout(x){A.innerHTML='<header><button data-p="home">berged</button><div><button data-a="notice">◔</button><button class="avatar" data-p="profile">B</button></div></header><main>'+x+'</main><nav><button data-p="home">⌂<small>Akış</small></button><button data-p="discover">◇<small>Keşfet</small></button><button class="plus" data-p="create">✦</button><button data-p="messages">◌<small>Mesaj</small></button><button data-p="profile">○<small>Ben</small></button></nav>';bind()}
function home(){return '<section class="hero"><div><label>BERGED</label><h1>Bugün ne<br>oluyor?</h1></div><button class="pill" data-p="create">Paylaş ↗</button></section><div class="friends">'+['Sen','Mira','Arda','Lina','Ege','Sena'].map((n,i)=>'<button data-p="'+(i?'home':'create')+'"><b>'+n[0]+'</b><small>'+n+'</small></button>').join('')+'</div><div class="heading"><div><label>AKIŞ</label><h2>Senden ve arkadaşlarından</h2></div></div><section class="feed">'+s.posts.map((p,i)=>'<article><div class="posthead"><b>'+p[0][0]+'</b><span><strong>'+esc(p[0])+'</strong><small>'+p[1]+' · şimdi</small></span><i>•••</i></div><p>'+esc(p[2])+'</p><div class="media"><span>BERGED / MOMENT</span><strong>'+(i?'20:30':'✦')+'</strong></div><footer><button data-like="'+i+'">♡ '+p[3]+'</button><button>○ 4</button><button>↗</button><button>⌁</button></footer></article>').join('')+'</section>'}
function discover(){return '<section class="intro"><label>KEŞFET</label><h1>Kaydır.<br>Keşfet.<br>Kal.</h1><p>Kısa videolar, yeni insanlar ve arkadaşlarının dünyasından anlar.</p></section><section class="videos">'+['Birlikte daha fazla an.','Berged’de bugün.','Arkadaşını etiketle.'].map((x,i)=>'<article class="v'+i+'"><span>berged · '+(i+1)+'/3</span><div><b>'+(i?'◇':'✦')+'</b><h2>'+x+'</h2><small>@'+['mira','arda','lina'][i]+'</small></div><footer>♡　○　↗</footer></article>').join('')+'</section>'}
function messages(){return '<section class="intro"><label>MESAJLAR</label><h1>İnsanların<br>burada.</h1></section><section class="chats">'+s.messages.map((m,i)=>'<button data-chat="'+i+'"><b>'+m[0][0]+'</b><span><strong>'+esc(m[0])+'</strong><small>'+esc(m[1])+'</small></span><em>şimdi</em></button>').join('')+'</section><button class="float" data-a="newchat">＋</button>'}
function profile(){let t=s.expenses.reduce((a,x)=>a+x,0);return '<section class="profile"><b>B</b><label>PROFİL</label><h1>Berged kullanıcısı</h1><p>@berged-user</p><div><span><strong>'+s.posts.length+'</strong> paylaşım</span><span><strong>128</strong> takipçi</span><span><strong>84</strong> takip</span></div></section><section class="cards"><button data-p="messages">◌<strong>Mesajlar</strong><small>Konuşmaların</small></button><button data-a="wallet">₺<strong>Harcamalar</strong><small>'+t.toFixed(2)+' ₺ kayıtlı</small></button><button data-a="streak">🔥<strong>Seriler</strong><small>Aktif serilerin</small></button><button data-a="settings">⋮<strong>Ayarlar</strong><small>Hesap ve tercihler</small></button></section>'}
function create(){return '<section class="intro"><label>YENİ AN</label><h1>Ne paylaşmak<br>istiyorsun?</h1></section><section class="cards create"><button data-a="text">✦<strong>Bir şey yaz</strong><small>Durumunu paylaş</small></button><button data-a="photo">□<strong>Fotoğraf / video</strong><small>Cihazından seç</small></button><button data-a="expense">₺<strong>Harcama ekle</strong><small>Yerel kaydına ekle</small></button></section>'}
function modal(title,body){let d=document.createElement('div');d.className='back';d.innerHTML='<div class="modal"><button class="x">×</button><label>BERGED</label><h2>'+title+'</h2>'+body+'</div>';document.body.append(d);d.querySelector('.x').onclick=()=>d.remove();return d}
function act(a){if(a==='notice')return modal('Bildirimler','<p>Şimdilik yeni bildirimin yok.</p>');if(a==='text')return modal('Bir şey yaz','<textarea id="txt" placeholder="Aklından ne geçiyor?"></textarea><button class="primary" id="pub">Gerçekten paylaş</button>');if(a==='photo')return modal('Fotoğraf / video','<input type="file" accept="image/*,video/*"><p>Dosya seçimi cihazından yapılır. Sunucu depolaması backend aşamasında bağlanacak.</p>');if(a==='expense')return modal('Harcama ekle','<input id="en" placeholder="Ne için?"><input id="ea" type="number" placeholder="Tutar (₺)"><button class="primary" id="exp">Kaydet</button>');if(a==='wallet')return modal('Harcamalar','<h3>'+s.expenses.reduce((a,x)=>a+x,0).toFixed(2)+' ₺</h3><p>Bu sürüm gerçek para transferi yapmaz.</p>');if(a==='streak')return modal('Seriler',s.streaks.map(x=>'<p>🔥 '+x[0]+' — <b>'+x[1]+' gün</b></p>').join(''));if(a==='settings')return modal('Ayarlar','<p>Gerçek hesap sistemiyle bağlanacak.</p>');if(a==='newchat')return modal('Yeni konuşma','<input id="cn" placeholder="Kullanıcı adı"><button class="primary" id="chat">Başlat</button>')}
function bind(){document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{s.page=b.dataset.p;save();render()});document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>act(b.dataset.a));document.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>{s.posts[b.dataset.like][3]++;save();render()});document.querySelectorAll('[data-chat]').forEach(b=>{b.onclick=()=>{let m=s.messages[b.dataset.chat];let d=modal(m[0],'<p>'+esc(m[1])+'</p><input id="reply" placeholder="Mesaj yaz..."><button class="primary" id="send">Gönder</button>');d.querySelector('#send').onclick=()=>{let v=d.querySelector('#reply').value.trim();if(v){m[1]=v;save();d.remove();render()}}}})}
document.addEventListener('click',e=>{if(e.target.id==='pub'){let v=document.querySelector('#txt').value.trim();if(v){s.posts.unshift(['Sen','@berged-user',v,0]);e.target.closest('.back').remove();s.page='home';render()}}if(e.target.id==='exp'){let v=Number(document.querySelector('#ea').value);if(v){s.expenses.push(v);save();e.target.closest('.back').remove();s.page='profile';render()}}if(e.target.id==='chat'){let n=document.querySelector('#cn').value.trim();if(n){s.messages.unshift([n,'Yeni konuşma']);e.target.closest('.back').remove();s.page='messages';render()}}});
function render(){save();layout(s.page==='home'?home():s.page==='discover'?discover():s.page==='messages'?messages():s.page==='profile'?profile():create())}render();